var myChart=echarts.init(document.getElementById('map2'))
var option = {
    backgroundColor:'#00102a',
    tooltip : {
        trigger: 'item',
        formatter : function (params) {
            var value = (params.value + '').split('.');
            value = value[0].replace(/(\d{1,3})(?=(?:\d{3})+(?!\d))/g, '$1,')
                + '.' + value[1];
            return params.seriesName + '<br/>' + params.name + ' : ' + value + '‰';
        }
    },
    toolbox: {
        show : true,
        orient : 'vertical',
        x: 'right',
        y: 'center',
        feature : {
            mark : {show: true},
            dataView : {show: true, readOnly: false},
            restore : {show: true},
            saveAsImage : {show: true}
        }
    },
    dataRange: {
        min: 0,
        max: 200,
        text:['High','Low'],
        textStyle: {
          color:'#ffffff'
        },
        realtime: false,
        calculable : true,
        color: ['#c02886','#e47096','#f2b6cd'],
    },
    series : [
        {
            name: '世界青少年生育率（2020）',
            type: 'map',
            mapType: 'world',
            roam: true,
            mapLocation: {
                y : 60
            },
            itemStyle:{
                emphasis:{
                    label:{show:true},
                    areaColor: '#10d7ad'
                },
                areaColor: '#e6e6e6',
                borderColor: '#FFFFFF',
                borderWidth: 0.5,
            },
            data:[
                {name: 'Afghanistan', value: 57.509},
                {name: 'Africa Eastern and Southern', value: 91.74471235},
                {name: 'Africa Western and Central', value: 107.4325753},
                {name: 'Albania', value: 19.4332},
                {name: 'Algeria', value: 9.3594},
                {name: 'American Samoa', value: '-'},
                {name: 'Andorra', value: '-'},
                {name: 'Angola', value: 142.822},
                {name: 'Antigua and Barbuda', value: 39.929},
                {name: 'Arab World', value: 44.40661104},
                {name: 'Argentina', value: 62.1322},
                {name: 'Armenia', value: 19.678},
                {name: 'Aruba', value: 18.1728},
                {name: 'Australia', value: 10.5474},
                {name: 'Austria', value: 6.4532},
                {name: 'Azerbaijan', value: 57.8168},
                {name: 'Bahamas, The', value: 27.6742},
                {name: 'Bahrain', value: 12.981},
                {name: 'Bangladesh', value: 81.0144},
                {name: 'Barbados', value: 26.2906},
                {name: 'Belarus', value: 12.2408},
                {name: 'Belgium', value: 4.4092},
                {name: 'Belize', value: 67.173},
                {name: 'Benin', value: 79.9172},
                {name: 'Bermuda', value: '-'},
                {name: 'Bhutan', value: 16.317},
                {name: 'Bolivia', value: 61.9126},
                {name: 'Bosnia and Herz.', value: 8.163},
                {name: 'Botswana', value: 43.952},
                {name: 'Brazil', value: 55.4354},
                {name: 'British Virgin Islands', value: '-'},
                {name: 'Brunei Darussalam', value: 8.5908},
                {name: 'Bulgaria', value: 38.2598},
                {name: 'Burkina Faso', value: 97.5394},
                {name: 'Burundi', value: 53.0748},
                {name: 'Cabo Verde', value: 70.5658},
                {name: 'Cambodia', value: 51.8072},
                {name: 'Cameroon', value: 98.8814},
                {name: 'Canada', value: 7.3298},
                {name: 'Caribbean small states', value: 47.65514634},
                {name: 'Cayman Islands', value: '-'},
                {name: 'Central African Rep.', value: 122.7428},
                {name: 'Central Europe and the Baltics', value: 18.90801699},
                {name: 'Chad', value: 151.5632},
                {name: 'Channel Islands', value: 6.1878},
                {name: 'Chile', value: 38.3112},
                {name: 'China', value: 7.659},
                {name: 'Colombia', value: 63.144},
                {name: 'Comoros', value: 61.4798},
                {name: 'Dem. Rep. Congo', value: 119.3768},
                {name: 'Congo', value: 108.3488},
                {name: 'Costa Rica', value: 50.6358},
                {name: "Côte d'Ivoire", value: 113.2212},
                {name: 'Croatia', value: 7.4336},
                {name: 'Cuba', value: 51.3628},
                {name: 'Curacao', value: 26.9586},
                {name: 'Cyprus', value: 4.2118},
                {name: 'Czech Rep.', value: 11.8502},
                {name: 'Denmark', value: 4.261},
                {name: 'Djibouti', value: 17.6482},
                {name: 'Dominica', value: '-'},
                {name: 'Dominican Rep.', value: 90.5826},
                {name: 'Early-demographic dividend', value: 34.54576489},
                {name: 'East Asia & Pacific', value: 20.59664414},
                {name: 'East Asia & Pacific (excluding high income)', value: 22.0193113},
                {name: 'East Asia & Pacific (IDA & IBRD countries)', value: 22.32753368},
                {name: 'Ecuador', value: 77.7658},
                {name: 'Egypt', value: 51.62},
                {name: 'El Salvador', value: 66.9228},
                {name: 'Eq. Guinea', value: 149.1132},
                {name: 'Eritrea', value: 47.0024},
                {name: 'Estonia', value: 5.9004},
                {name: 'Swaziland', value: 72.6762},
                {name: 'Ethiopia', value: 61.7704},
                {name: 'Euro area', value: 6.180599847},
                {name: 'Europe & Central Asia', value: 15.7635951},
                {name: 'Europe & Central Asia (excluding high income)', value: 23.9373761},
                {name: 'Europe & Central Asia (IDA & IBRD countries)', value: 23.25561255},
                {name: 'European Union', value: 8.569623923},
                {name: 'Faroe Islands', value: '-'},
                {name: 'Fiji', value: 48.7158},
                {name: 'Finland', value: 5.3504},
                {name: 'Fragile and conflict affected situations', value: 85.55298166},
                {name: 'France', value: 4.7546},
                {name: 'French Polynesia', value: 38.085},
                {name: 'Gabon', value: 88.2392},
                {name: 'Gambia, The', value: 70.7474},
                {name: 'Georgia', value: 42.7384},
                {name: 'Germany', value: 7.3804},
                {name: 'Ghana', value: 64.1306},
                {name: 'Gibraltar', value: '-'},
                {name: 'Greece', value: 6.3668},
                {name: 'Greenland', value: '-'},
                {name: 'Grenada', value: 26.2274},
                {name: 'Guam', value: 28.3938},
                {name: 'Guatemala', value: 67.408},
                {name: 'Guinea', value: 129.507},
                {name: 'Guinea-Bissau', value: 100.0296},
                {name: 'Guyana', value: 69.8406},
                {name: 'Haiti', value: 49.5088},
                {name: 'Heavily indebted poor countries (HIPC)', value: 96.49902371},
                {name: 'High income', value: 11.19285329},
                {name: 'Honduras', value: 69.7152},
                {name: 'Hong Kong SAR, China', value: 2.5286},
                {name: 'Hungary', value: 24.8688},
                {name: 'IBRD only', value: 26.44116477},
                {name: 'Iceland', value: 5.1818},
                {name: 'IDA & IBRD total', value: 44.84766751},
                {name: 'IDA blend', value: 69.56876637},
                {name: 'IDA only', value: 87.15478562},
                {name: 'IDA total', value: 81.41178521},
                {name: 'India', value: 9.8584},
                {name: 'Indonesia', value: 45.9676},
                {name: 'Iran', value: 40.8096},
                {name: 'Iraq', value: 71.7588},
                {name: 'Ireland', value: 6.1398},
                {name: 'Isle of Man', value: '-'},
                {name: 'Israel', value: 8.362},
                {name: 'Italy', value: 4.85},
                {name: 'Jamaica', value: 48.4418},
                {name: 'Japan', value: 3.4332},
                {name: 'Jordan', value: 25.7702},
                {name: 'Kazakhstan', value: 28.592},
                {name: 'Kenya', value: 71.976},
                {name: 'Kiribati', value: 13.8598},
                {name: 'Dem. Rep. Korea', value: 0.292},
                {name: 'Korea', value: 1.2032},
                {name: 'Kosovo', value: '-'},
                {name: 'Kuwait', value: 7.2694},
                {name: 'Kyrgyzstan', value: 31.7982},
                {name: 'Lao PDR', value: 63.997},
                {name: 'Late-demographic dividend', value: 19.85929533},
                {name: 'Latin America & Caribbean', value: 60.26488613},
                {name: 'Latin America & Caribbean (excluding high income)', value: 59.72592333},
                {name: 'Latin America & the Caribbean (IDA & IBRD countries)', value: 60.55002326},
                {name: 'Latvia', value: 15.0622},
                {name: 'Least developed countries: UN classification', value: 90.22414767},
                {name: 'Lebanon', value: 13.6714},
                {name: 'Lesotho', value: 92.282},
                {name: 'Liberia', value: 134.7746},
                {name: 'Libya', value: 5.6064},
                {name: 'Liechtenstein', value: '-'},
                {name: 'Lithuania', value: 8.8998},
                {name: 'Low & middle income', value: 44.65599413},
                {name: 'Low income', value: 92.46893007},
                {name: 'Lower middle income', value: 40.81662442},
                {name: 'Luxembourg', value: 4.3574},
                {name: 'Macao SAR, China', value: 2.1488},
                {name: 'Madagascar', value: 104.0322},
                {name: 'Malawi', value: 130.9424},
                {name: 'Malaysia', value: 13.5724},
                {name: 'Maldives', value: 6.6214},
                {name: 'Mali', value: 162.3464},
                {name: 'Malta', value: 11.7318},
                {name: 'Marshall Islands', value: '-'},
                {name: 'Mauritania', value: 66.786},
                {name: 'Mauritius', value: 24.3658},
                {name: 'Mexico', value: 57.6326},
                {name: 'Micronesia, Fed. Sts.', value: 11.8342},
                {name: 'Middle East & North Africa', value: 39.02823088},
                {name: 'Middle East & North Africa (excluding high income)', value: 42.90694589},
                {name: 'Middle East & North Africa (IDA & IBRD countries)', value: 42.79676666},
                {name: 'Middle income', value: 36.73861076},
                {name: 'Moldova', value: 21.7106},
                {name: 'Monaco', value: '-'},
                {name: 'Mongolia', value: 32.3292},
                {name: 'Montenegro', value: 7.717},
                {name: 'Morocco', value: 29.975},
                {name: 'Mozambique', value: 141.5004},
                {name: 'Myanmar', value: 27.6018},
                {name: 'Namibia', value: 57.642},
                {name: 'Nauru', value: '-'},
                {name: 'Nepal', value: 62.955},
                {name: 'Netherlands', value: 3.5324},
                {name: 'New Caledonia', value: 13.7056},
                {name: 'New Zealand', value: 17.2738},
                {name: 'Nicaragua', value: 79.9344},
                {name: 'Niger', value: 177.4642},
                {name: 'Nigeria', value: 101.681},
                {name: 'North America', value: 15.20890962},
                {name: 'Macedonia', value: 14.04},
                {name: 'Northern Mariana Islands', value: '-'},
                {name: 'Norway', value: 5.0324},
                {name: 'Not classified', value: '-'},
                {name: 'OECD members', value: 20.84297346},
                {name: 'Oman', value: 11.9772},
                {name: 'Other small states', value: 58.22183295},
                {name: 'Pacific island small states', value: 50.54056078},
                {name: 'Pakistan', value: 37.0278},
                {name: 'Palau', value: '-'},
                {name: 'Panama', value: 79.4598},
                {name: 'Papua New Guinea', value: 50.636},
                {name: 'Paraguay', value: 69.5392},
                {name: 'Peru', value: 54.0914},
                {name: 'Philippines', value: 55.9696},
                {name: 'Poland', value: 9.4316},
                {name: 'Portugal', value: 7.2436},
                {name: 'Post-demographic dividend', value: 10.88656414},
                {name: 'Pre-demographic dividend', value: 103.4846594},
                {name: 'Puerto Rico', value: 26.7244},
                {name: 'Qatar', value: 8.9248},
                {name: 'Romania', value: 34.183},
                {name: 'Russia', value: 17.4608},
                {name: 'Rwanda', value: 38.328},
                {name: 'Samoa', value: 22.1136},
                {name: 'San Marino', value: '-'},
                {name: 'Sao Tome and Principe', value: 90.7928},
                {name: 'Saudi Arabia', value: 6.643},
                {name: 'Senegal', value: 66.698},
                {name: 'Serbia', value: 13.0212},
                {name: 'Seychelles', value: 59.5732},
                {name: 'Sierra Leone', value: 105.0286},
                {name: 'Singapore', value: 3.4802},
                {name: 'Sint Maarten (Dutch part)', value: '-'},
                {name: 'Slovakia', value: 26.4376},
                {name: 'Slovenia', value: 3.4052},
                {name: 'Small states', value: 55.93929271},
                {name: 'Solomon Is.', value: 79.2288},
                {name: 'Somalia', value: 92.7656},
                {name: 'South Africa', value: 67.7304},
                {name: 'South Asia', value: 22.35726589},
                {name: 'South Asia (IDA & IBRD)', value: 22.35726589},
                {name: 'S. Sudan', value: 54.2196},
                {name: 'Spain', value: 7.0212},
                {name: 'Sri Lanka', value: 20.2192},
                {name: 'St. Kitts and Nevis', value: '-'},
                {name: 'St. Lucia', value: 38.5656},
                {name: 'St. Martin (French part)', value: '-'},
                {name: 'St. Vincent and the Grenadines', value: 46.5294},
                {name: 'Sub-Saharan Africa', value: 98.03240066},
                {name: 'Sub-Saharan Africa (excluding high income)', value: 98.03440415},
                {name: 'Sub-Saharan Africa (IDA & IBRD countries)', value: 98.03240066},
                {name: 'Sudan', value: 54.402},
                {name: 'Suriname', value: 58.6088},
                {name: 'Sweden', value: 5.2158},
                {name: 'Switzerland', value: 2.4054},
                {name: 'Syria', value: 36.6696},
                {name: 'Tajikistan', value: 58.2598},
                {name: 'Tanzania', value: 114.008},
                {name: 'Thailand', value: 44.2504},
                {name: 'Timor-Leste', value: 29.522},
                {name: 'Togo', value: 87.8814},
                {name: 'Tonga', value: 13.6666},
                {name: 'Trinidad and Tobago', value: 27.8214},
                {name: 'Tunisia', value: 7.868},
                {name: 'Turkey', value: 23.5494},
                {name: 'Turkmenistan', value: 23.8612},
                {name: 'Turks and Caicos Islands', value: '-'},
                {name: 'Tuvalu', value: '-'},
                {name: 'Uganda', value: 110.5422},
                {name: 'Ukraine', value: 21.5858},
                {name: 'United Arab Emirates', value: 4.5684},
                {name: 'United Kingdom', value: 11.183},
                {name: 'United States', value: 15.9486},
                {name: 'Upper middle income', value: 29.03892595},
                {name: 'Uruguay', value: 57.2618},
                {name: 'Uzbekistan', value: 25.0482},
                {name: 'Vanuatu', value: 47.8506},
                {name: 'Venezuela', value: 84.2636},
                {name: 'Vietnam', value: 25.5974},
                {name: 'Virgin Islands (U.S.)', value: 25.1706},
                {name: 'West Bank and Gaza', value: 50.1164},
                {name: 'World', value: 41.03715165},
                {name: 'Yemen', value: 56.7832},
                {name: 'Zambia', value: 114.6904},
                {name: 'Zimbabwe', value: 77.4758}
            ]
        }
    ]
};
myChart.setOption(option)
